default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: librarymain_development

test:
  <<: *default
  database: librarymain_test

production:
  <<: *default
  database: librarymain_production
  username: librarymain
  password: <%= ENV['LIBRARYMAIN_DATABASE_PASSWORD'] %>
